# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: malinskiy/action-android/install-sdk@release/0.0.5
    - run: echo $ANDROID_HOME
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: SDK Manager
      run: sdkmanager 'ndk;20.0.5594570'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
